# Generated by Django 4.1.3 on 2025-07-09 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the article (max 200 characters)', max_length=200)),
                ('content', models.TextField(help_text='The main content/body of the article')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated)', max_length=250, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Current status of the article', max_length=10)),
                ('publish_date', models.DateTimeField(blank=True, help_text='Optional future date when the article should be published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the article was last updated')),
                ('author', models.ForeignKey(help_text='The user who created this article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='blog_articl_status_39d3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='blog_articl_author__00152e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
    ]
